# cluster.yaml
# An example of ClusterConfig containing Windows and Linux node groups to support Windows workloads
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: leonj-aws-meetup
  region: ap-southeast-1

nodeGroups:
  - name: windows-nodes
    amiFamily: WindowsServer2019FullContainer
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
  - name: linux-nodes
    instanceType: t2.large
    minSize: 1
    maxSize: 3
    desiredCapacity: 2