apiVersion: v1
kind: Service
metadata:
  name: multiplication-service
spec:
  type: NodePort
  ports:
  - name: multiplication-service
    port: 30003
    targetPort: 3000
    nodePort: 30003
  selector:
    app: multiplication-service
  
