apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calculator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
      name: calculator-app
    spec:
      containers:
      - name: calculator-app
        image: leonjalfon1/aws-meetup-hybrid-microservices:hybrid
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: "SERVICE_IP"
          value: "18.136.205.8"  # IP OF A CLUSTER NODE
        - name: "SERVICE_PORT"
          value: "30000"
        - name: "SUM_SERVICE_IP"
          value: "18.136.205.8" 
        - name: "SUM_SERVICE_PORT"
          value: "30001"
        - name: "SUBTRACTION_SERVICE_IP"
          value: "18.136.205.8"  
        - name: "SUBTRACTION_SERVICE_PORT"
          value: "30002"
      nodeSelector:
        beta.kubernetes.io/os: windows
