apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sum-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subtraction-service
  template:
    metadata:
      labels:
        app: subtraction-service
      name: subtraction-service
    spec:
      containers:
      - name: subtraction-service
        image: leonjalfon1/aws-meetup-hybrid-microservices:subtraction-service
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      nodeSelector:
        beta.kubernetes.io/os: linux
