apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: division-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: division-service
  template:
    metadata:
      labels:
        app: division-service
      name: division-service
    spec:
      containers:
      - name: division-service
        image: leonjalfon1/aws-meetup-hybrid-microservices:division-service
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      nodeSelector:
        beta.kubernetes.io/os: linux
